src/FLSHR/gestionPublicationBundle/Entity/Ouvrage.php
<?php

namespace FLSHR\gestionPublicationBundle\Entity;
use Symfony\Component\HttpFoundation\File\UploadedFile;

use Doctrine\ORM\Mapping as ORM;


/**
 * Ouvrage
 *
 * @ORM\Table(name="ouvrage")
 * @ORM\HasLifecycleCallbacks
 * @ORM\Entity(repositoryClass="FLSHR\gestionPublicationBundle\Entity\OuvrageRepository")
 */
class Ouvrage
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="titre", type="string", length=1024, nullable=true)
     */
    private $titre;

    /**
     * @var string
     *
     * @ORM\Column(name="auteur", type="string", length=1024, nullable=true)
     */
    private $auteur;

    /**
     * @var string
     *
     * @ORM\Column(name="editeur", type="string", length=1024, nullable=true)
     */
    private $editeur;

    /**
     * @var string
     *
     * @ORM\Column(name="serie", type="string", length=1024, nullable=true)
     */
    private $serie;

    /**
     * @var string
     *
     * @ORM\Column(name="impression", type="string", length=254, nullable=true)
     */
    private $impression;

    /**
     * @var string
     *
     * @ORM\Column(name="depot_legal", type="string", length=1024, nullable=true)
     */
    private $depotLegal;

    /**
     * @var string
     *
     * @ORM\Column(name="isbn", type="string", length=254, nullable=true)
     */
    private $isbn;

    /**
     * @var string
     *
     * @ORM\Column(name="issn", type="string", length=254, nullable=true)
     */
    private $issn;

    /**
     * @var string
     *
     * @ORM\Column(name="edition", type="string", length=254, nullable=true)
     */
    private $edition;

    /**
     * @var float
     *
     * @ORM\Column(name="prix", type="decimal", nullable=true)
     */
    private $prix;

    /**
     * @var integer
     *
     * @ORM\Column(name="qutestocke", type="integer", nullable=true)
     */
    private $qutestocke;

    /**
     * @var string
     *
     * @ORM\Column(name="photo", type="string", length=254, nullable=true)
     */
    private $photo;

    /**
     * @var string
     *
     * @ORM\Column(name="descrption", type="string", length=1024, nullable=true)
     */
    private $descrption;

    /**
     * @var \Datetime
     *
     * @ORM\Column(name="dateentree", type="date", nullable=true)
     */
    private $dateentree;

    /**
     * @var string
     *
     * @ORM\Column(name="etat", type="string", length=254, nullable=true)
     */
     private $etat;
     
    /**
    * @ORM\OneToMany(targetEntity="FLSHR\GestionPublicationBundle\Entity\detailscommande" ,mappedBy="ouvrage")
    */
    private $detailcomande;
    
    
    private $file;
     
    // On ajoute cet attribut pour y stocker le nom du fichier temporairement
    private $tempFilename;
  

    // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
    public function setFile(UploadedFile $file)
     {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->photo) {
          // On sauvegarde l'extension du fichier pour le supprimer plus tard
          $this->tempFilename = $this->photo;

          // On réinitialise les valeurs des attributs url et alt
          $this->photo = null;
        }
     }
     
     public function getFile()
     {
         return $this->file ;
     }


     /**
    * @ORM\PrePersist()
    * @ORM\PreUpdate()
    */
   public function preUpload()
   {
     // Si jamais il n'y a pas de fichier (champ facultatif)
     if (null === $this->file) {
       return;
     }

     // Le nom du fichier est son id, on doit juste stocker également son extension
     // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
     //$this->photo = $this->file->guessExtension();

     // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
     $this->photo = $this->file->getClientOriginalName();
   }
     
  /**
   * @ORM\PostPersist()
   * @ORM\PostUpdate()
   */
  public function upload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif)
    if (null === $this->file) {
      return;
    }
 
    // Si on avait un ancien fichier, on le supprime
    if (null !== $this->tempFilename) {
      $oldFile = $this->getUploadRootDir().'/'.$this->id.'_'.$this->tempFilename;
      if (file_exists($oldFile)) {
        unlink($oldFile);
      }
    }
 
    // On déplace le fichier envoyé dans le répertoire de notre choix
    $this->file->move(
      $this->getUploadRootDir(), // Le répertoire de destination
      $this->id.'_'.$this->photo   // Le nom du fichier à créer, ici « id.extension »
    );
  }
  
  /**
   * @ORM\PreRemove()
   */
  public function preRemoveUpload()
  {
    // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
    $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'_'.$this->photo;
  }
 
  /**
   * @ORM\PostRemove()
   */
  public function removeUpload()
  {
    // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
    if (file_exists($this->tempFilename)) {
      // On supprime le fichier
      unlink($this->tempFilename);
    }
  }
  
      public function getWebPath()
        {
          return $this->getUploadDir().'/'.$this->getId().'_'.$this->getPhoto();
        }
  
    /**
     * Constructor
     */
    public function __construct()
    {
         $this->detailcomande = new \Doctrine\Common\Collections\ArrayCollection();
    }
   
 
  public function getUploadDir()
  {
    // On retourne le chemin relatif vers l'image pour un navigateur
    return 'uploads/img';
  }
 
  protected function getUploadRootDir()
  {
    // On retourne le chemin relatif vers l'image pour notre code PHP
    return __DIR__.'/../../../../web/'.$this->getUploadDir();
  }
    

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set titre
     *
     * @param string $titre
     * @return Ouvrage
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;
    
        return $this;
    }

    /**
     * Get titre
     *
     * @return string 
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * Set auteur
     *
     * @param string $auteur
     * @return Ouvrage
     */
    public function setAuteur($auteur)
    {
        $this->auteur = $auteur;
    
        return $this;
    }

    /**
     * Get auteur
     *
     * @return string 
     */
    public function getAuteur()
    {
        return $this->auteur;
    }

    /**
     * Set editeur
     *
     * @param string $editeur
     * @return Ouvrage
     */
    public function setEditeur($editeur)
    {
        $this->editeur = $editeur;
    
        return $this;
    }

    /**
     * Get editeur
     *
     * @return string 
     */
    public function getEditeur()
    {
        return $this->editeur;
    }

    /**
     * Set serie
     *
     * @param string $serie
     * @return Ouvrage
     */
    public function setSerie($serie)
    {
        $this->serie = $serie;
    
        return $this;
    }

    /**
     * Get serie
     *
     * @return string 
     */
    public function getSerie()
    {
        return $this->serie;
    }

    /**
     * Set impression
     *
     * @param string $impression
     * @return Ouvrage
     */
    public function setImpression($impression)
    {
        $this->impression = $impression;
    
        return $this;
    }

    /**
     * Get impression
     *
     * @return string 
     */
    public function getImpression()
    {
        return $this->impression;
    }

    /**
     * Set depotLegal
     *
     * @param string $depotLegal
     * @return Ouvrage
     */
    public function setDepotLegal($depotLegal)
    {
        $this->depotLegal = $depotLegal;
    
        return $this;
    }

    /**
     * Get depotLegal
     *
     * @return string 
     */
    public function getDepotLegal()
    {
        return $this->depotLegal;
    }

    /**
     * Set isbn
     *
     * @param string $isbn
     * @return Ouvrage
     */
    public function setIsbn($isbn)
    {
        $this->isbn = $isbn;
    
        return $this;
    }

    /**
     * Get isbn
     *
     * @return string 
     */
    public function getIsbn()
    {
        return $this->isbn;
    }

    /**
     * Set issn
     *
     * @param string $issn
     * @return Ouvrage
     */
    public function setIssn($issn)
    {
        $this->issn = $issn;
    
        return $this;
    }

    /**
     * Get issn
     *
     * @return string 
     */
    public function getIssn()
    {
        return $this->issn;
    }

    /**
     * Set edition
     *
     * @param string $edition
     * @return Ouvrage
     */
    public function setEdition($edition)
    {
        $this->edition = $edition;
    
        return $this;
    }

    /**
     * Get edition
     *
     * @return string 
     */
    public function getEdition()
    {
        return $this->edition;
    }

    /**
     * Set prix
     *
     * @param float $prix
     * @return Ouvrage
     */
    public function setPrix($prix)
    {
        $this->prix = $prix;
    
        return $this;
    }

    /**
     * Get prix
     *
     * @return float 
     */
    public function getPrix()
    {
        return $this->prix;
    }

    /**
     * Set qutestocke
     *
     * @param integer $qutestocke
     * @return Ouvrage
     */
    public function setQutestocke($qutestocke)
    {
        $this->qutestocke = $qutestocke;
    
        return $this;
    }

    /**
     * Get qutestocke
     *
     * @return integer 
     */
    public function getQutestocke()
    {

src/FLSHR/gestionPublicationBundle/Form/OuvrageType.php
<?php

namespace FLSHR\gestionPublicationBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class OuvrageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre' , 'text' , array('label' => 'Titre' ))
            ->add('auteur' , 'text' , array('label' => 'Auteur'))
            ->add('editeur' ,'text' , array('label' => 'Editeur' , 'read_only'=>true))
            ->add('serie' ,'text' , array('label' => 'série' , 'required'=> false))
            ->add('impression' , 'text' , array('label' => 'Impression' , 'required'=>false))
            ->add('depotLegal' , 'text' , array('label' => 'Depot légal' , 'required'=> false ))
            ->add('isbn' , 'text' , array('label' => 'ISBN',"required"=> false))
            ->add('issn' , 'text' , array('label' => 'ISSN' , "required"=> false))
            ->add('edition' , 'text' , array('label' => 'Edition' , "required"=> false))
            ->add('prix' , 'integer' , array('label' => 'Prix' , "required"=> true))
            ->add('qutestocke' , 'integer' , array('label' => 'Quantité stockée' , "required"=> true))
            ->add('file' , 'file' , array('label' => 'Photo' ,"required"=> false))
            ->add('descrption' , 'textarea' , array('label' => 'Discription' , "required"=> false))
            ->add('dateentree' ,'date' , array('label' => 'Date d\'entrée' , "required"=> false))
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'FLSHR\gestionPublicationBundle\Entity\Ouvrage'
        ));
    }

    public function getName()
    {
        return 'flshr_gestionpublicationbundle_ouvragetype';
    }
}

src/FLSHR/gestionPublicationBundle/Resources/views/Ouvrage/accueil.html.twig
{% extends 'GestionPublicationBundle::gestionPublication/base.html.twig' %}
{% block title %}FLSHR Gestion des publications | Accueil{% endblock %} 
{%block connection %}
<div style="float:right;padding-top:20px">
<ul class="nav">
<li><a href="{{ path('fos_user_security_logout') }}"><span class="icon16 icomoon-icon-exit"></span>Se déconnecter</a></li>
</ul>          
</div>
{% endblock %}
{% block content %}
        <div id="content" class="clearfix">
            <div class="contentwrapper">

<div class="heading">
<h3>Accueil</h3>                    
</div>
                <div class="row-fluid">
				<h2>Bienvenue {{ app.user.username }}, <br>
				pour passer une commande, cliquez sur le bouton ci-dessous</h2>
							<div align="center" style="padding-top:30px;">
							<a href="{{ path('gestion_publication_liste_ouvrage_accueil') }}" class="btn btn-warning btn-large">
                                                            <i class="icon-white icon-share"></i> 
                                                           Passer une commande</a>
                                                        </div>
		</div>
            </div>
        </div>
{% endblock %}

src/FLSHR/gestionPublicationBundle/Resources/views/Ouvrage/index.html.twig
{% extends 'GestionPublicationBundle::gestionPublication/base.html.twig' %}
{% block title %}FLSHR Gestion des publications{% endblock %}
{% block sidebar %} {% endblock %}
{%block connection %}
<div style="float:right;padding-top:20px">
    <ul class="nav">
        <li><a href="{{ path('fos_user_security_login') }}"><span class="icon16 icomoon-icon-exit"></span> Se connecter</a></li>
    </ul>          
</div>
{% endblock %}
{% block content %}
<div id="content-home" >
    <div class="contentwrapper">
        <div class="heading">
            <div class="resBtnSearch">
                <a href="#"><span class="icon16 icomoon-icon-search-3"></span></a>
            </div>
            <div class="search">

                <form id="searchform">
                    <input type="text" name="motcle"  id="tipue_search_input" class="top-search" placeholder="Rechercher ..." />
                    <input type="submit" id="tipue_search_button" class="search-btn" value=""/>
                </form>

            </div>
        </div>
        <div style="margin-left: auto;margin-right: auto;text-align:center;">
            <ul class="hProductItems clearfix">
                <table width="100%"><tr>
                                                            {% set newline=0 %}
                                                            {% for entity in entities %}
                                <td style="display: inline-block;margin-left:40px;margin-bottom: 3px;">
                                    <form action="{{ path('gestion_publication_add_panier', { 'id': entity.id }) }}" method="post" >
                                        <div class="thumbnail">
										{% if entity.photo=="" %}
                                                <a href="{{ asset('images/livre.jpg') }}?lightbox[width]=383&lightbox[height]=476"  
                                                   title="Titre : {{ entity.titre }}<br>
                                                   Auteur : {{ entity.auteur }}<br>
                                                   Editeur : {{ entity.editeur }}<br>
                                                   Serie : {{ entity.serie }}<br>
                                                   Edition : {{ entity.edition }}<br>
                                                   Prix : {{ entity.prix }}<br>
                                                   ISBN : {{ entity.isbn }}<br>
                                                   ISSN : {{ entity.issn }}<br>
                                                   Impression : {{ entity.impression }}"
                                                   onmouseover="this.setAttribute('org_title', this.title);
                                           this.title = '{{ entity.titre }}';" 
                                                   onmouseout="this.title = this.getAttribute('org_title');" 
                                                   onclick="this.title = this.getAttribute('org_title');"  
                                                   class="lightbox" ><img src="{{ asset('images/livre.jpg') }}" alt="" style="width:143px;height:192px"></a>
                                                                                {% else %}
                                                <a href="{{ asset(entity.webPath) }}?lightbox[width]=383&lightbox[height]=476" 
                                                   title="Titre : {{ entity.titre }}<br>
                                                   Auteur : {{ entity.auteur }}<br>
                                                   Editeur : {{ entity.editeur }}<br>
                                                   Serie : {{ entity.serie }}<br>
                                                   Edition : {{ entity.edition }}<br>
                                                   Prix : {{ entity.prix }}<br>
                                                   ISBN : {{ entity.isbn }}<br>
                                                   ISSN : {{ entity.issn }}<br>
                                                   Impression : {{ entity.impression }}"
                                                   onmouseover="this.setAttribute('org_title', this.title);
                                           this.title = '{{ entity.titre }}';" 
                                                   onmouseout="this.title = this.getAttribute('org_title');" 
                                                   onclick="this.title = this.getAttribute('org_title');" 
                                                   class="lightbox" ><img src="{{ asset(entity.webPath) }}" alt="" style="width:143px;height:192px"></a>
                                                                                {% endif %} 
                                            </div>

                                            <div class="thumbSetting">
                                                <div class="thumbTitle" style="height:60px;">
                                                    <a href="#" class="invarseColor">
                                                                                            {% if entity.titre|length > 50 %}
												{{ entity.titre|slice(0, 49) }} ...
                                                                                              {% else %}
                                                                                             {{ entity.titre }}
                                                                                            {% endif %}
                                                        </a>
                                                    </div>
                                                    <div class="thumbPrice">
                                                        <span>{{ entity.prix }} Dhs</span>
                                                    </div>
                                                </div>
                                                <hr style="color:#8C898A;background-color:#8C898A;height: 5px;">
                                            </form>  
                                        </td>
                                                        {% set newline= newline+1 %}
                                                        {% if newline==4 %}
                                                        {% set newline=0 %}
                                    </tr><tr>
                                                                        {% endif %}
                                                     {% endfor %}
                                    </table>
                           {% if entities|length != 0 %}
                                    <div class="pagination">
                                        <ul>
                          {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
                          {% for p in range(1, nombrePage) %}
                                                <li{% if p == page %} class="active"{% endif %}>
                                                    <a href="{{ path('ouvrage', {'page': p}) }}">{{ p }}</a>
                                                </li>
                          {% endfor %}
                                            </ul>
                                        </div>
                      {% endif %}
                                    </ul>

                                </div>

                            </div>
                        </div>
{% endblock %}

src/FLSHR/gestionPublicationBundle/Resources/views/Ouvrage/listeouvrageArchive.html.twig
{% extends 'GestionPublicationBundle::gestionPublication/base.html.twig' %}
{% block title %}FLSHR Gestion des publications | archive{% endblock %} 
{% block stylesheets %}
{{ parent() }}
        <link href="{{ asset('css/itoast.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset('css/pirobox/style.css') }}" rel="stylesheet" type="text/css" />
{% endblock %} 
  {%block connection %}
<div style="float:right;padding-top:20px">
    <ul class="nav">
        <li><a href="{{ path('fos_user_security_login') }}"><span class="icon16 icomoon-icon-exit"></span> Se connecter</a></li>
    </ul>          
</div>
{% endblock %}      
{% block content %}
{% set productexpire=0 %}
<div id="content" class="clearfix">
    <div class="contentwrapper">
        <div class="heading">
            <h3>Liste des ouvrages</h3>                    
            <div class="cmd">

            </div>
        </div> 
        <div class="row-fluid">
            <h2>&nbsp;</h2>
            <table class="responsive table table-bordered">
                <thead>
                    <tr>
                        <th>Titre</th>
                        <th>Auteur</th>
                        <th>Edition</th>
                        <th>ISBN</th>
                        <th>ISSN</th>
                        <th>Prix</th>
                    </tr>
                </thead>
                <tbody>
                                     {% for entity in entities|reverse %}
                        
                             <tr>
                            <td>{{ entity.titre }}</td>
                            <td>{{ entity.auteur }}</td>
                            <td>{{ entity.edition }}</td>
                            <td>{{ entity.isbn }}</td>
                            <td>{{ entity.issn }}</td>
                            <td>{{ entity.prix }} dhs</td>
                            
                        </tr>
                          
                                  {% endfor %}
                    </tbody>
                </table>
                <div class="pagination" style="width:900px;">
                    <ul>
                          {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
                          {% for p in range(1, nombrePage) %}
                            <li{% if p == page %} class="active"{% endif %}>
                                <a href="{{ path('ouvrage_afficher', {'page': p}) }}">{{ p }}</a>
                            </li>
                          {% endfor %}
                        </ul>
                </div>
                </div>
  
            </div>
        </div>
{% endblock %}

src/FLSHR/gestionPublicationBundle/Resources/views/Ouvrage/resultat.html.twig
<ul class="hProductItems clearfix" >
<table width="100%"><tr>
                                                            {% set newline=0 %}

                                                            {% for entity in entities %}
                <td style="display: inline-block;margin-left:40px;margin-bottom: 3px;">
                    <form action="{{ path('gestion_publication_add_panier', { 'id': entity.id }) }}" method="post" id="form">
                        <div class="thumbnail">
										{% if entity.photo=="" %}
                                <a href="{{ asset('images/livre.jpg') }}?lightbox[width]=383&lightbox[height]=476"  
                                   title="Titre : {{ entity.titre }}<br>
                                   Auteur : {{ entity.auteur }}<br>
                                   Editeur : {{ entity.editeur }}<br>
                                   Serie : {{ entity.serie }}<br>
                                   Edition : {{ entity.edition }}<br>
                                   Prix : {{ entity.prix }}<br>
                                   ISBN : {{ entity.isbn }}<br>
                                   ISSN : {{ entity.issn }}<br>
                                   Impression : {{ entity.impression }}"
                                   onmouseover="this.setAttribute('org_title', this.title);
                                           this.title = '{{ entity.titre }}';" 
                                   onmouseout="this.title = this.getAttribute('org_title');" 
                                   onclick="this.title = this.getAttribute('org_title');"  
                                   class="lightbox" ><img src="{{ asset('images/livre.jpg') }}" alt="" style="width:143px;height:192px"></a>
                                                                                {% else %}
                                <a href="{{ asset(entity.webPath) }}?lightbox[width]=383&lightbox[height]=476"  
                                   title="Titre : {{ entity.titre }}<br>
                                   Auteur : {{ entity.auteur }}<br>
                                   Editeur : {{ entity.editeur }}<br>
                                   Serie : {{ entity.serie }}<br>
                                   Edition : {{ entity.edition }}<br>
                                   Prix : {{ entity.prix }}<br>
                                   ISBN : {{ entity.isbn }}<br>
                                   ISSN : {{ entity.issn }}<br>
                                   Impression : {{ entity.impression }}"
                                   onmouseover="this.setAttribute('org_title', this.title);
                                           this.title = '{{ entity.titre }}';" 
                                   onmouseout="this.title = this.getAttribute('org_title');" 
                                   onclick="this.title = this.getAttribute('org_title');" 
                                   class="lightbox" ><img src="{{ asset(entity.webPath) }}" alt="" style="width:143px;height:192px"></a>
                                                                                {% endif %} 
                            </div>

                            <div class="thumbSetting">
                                <div class="thumbTitle" style="height:60px;">
                                    <a href="#" class="invarseColor">
                                                                                            {% if entity.titre|length > 50 %}
												{{ entity.titre|slice(0, 49) }} ...
                                                                                              {% else %}
                                                                                             {{ entity.titre }}
                                                                                            {% endif %}
                                        </a>
                                    </div>
                                    <div class="thumbPrice">
                                        <span>{{ entity.prix }} Dhs</span>
                                    </div>
                                    <div class="quantite">
                                                                                    {% set disabled="" %}
                                                                                    {% set btn="btn-primary" %}
                                                                                    {% if entity.qutestocke <= 10 %}
                                                                                         {% set disabled="disabled" %} 
                                                                                         {% set btn="btn-danger" %}
                                                                                    {% endif %}  
                                            <select name="quantite" {{ disabled }} >
                                                                                   {% for i in 1..entity.qutestocke-10 %}
                                                    <option  value="{{ i }}"> {{ i }}</option>
                                                                                    {% endfor %}
                                                </select>
                                            </div>
                                            <div >
                                                <button {{ disabled }}  type="submit" class="btn {{ btn }}"><i class="icon-white icon-shopping-cart"></i> Ajouter au panier</button>
                                            </div>
                                        </div>
                                        <hr style="color:#8C898A;background-color:#8C898A;height: 5px;">
                                    </form>  
                                </td>
                                                        {% set newline= newline+1 %}
                                                        {% if newline==4 %}
                                                        {% set newline=0 %}
                            </tr><tr>
                                                                        {% endif %}
                                                     {% endfor %}
                            </table>
                            {% if  page != 0 %}
                            <div class="pagination" style="width:900px;">
                                <ul>
                          {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
                          {% for p in range(1, nombrePage) %}
                                        <li{% if p == page %} class="active"{% endif %}>
                                            <a id="pag{{ p }}">{{ p }}</a>
                                        </li>
                          {% endfor %}
                                    </ul>
                                </div>


<script type="text/javascript" src="{{ asset('js/jquery1.8.3.min.js') }}"></script>
<script type="text/javascript">
    
        $(document).ready(function() {
            $("#loader").hide(); 
            {% for p in range(1, nombrePage) %}
$('#pag{{ p }}').click(function() {
$("#loading").show();
$('#reponse').hide();   
$.ajax({type: 'POST',
                url: "{{ path('gestion_publication_liste_ouvrage', {'page': p}) }}",
                data: $('#form').serialize(),
                success: function(data) {
                 $("#loading").fadeOut();            
                 $('#reponse').hide().html(data).fadeIn();
                }});        });
        {% endfor %}
       
}); 
</script>
                            {% endif %}
</ul>                            